# Prefer to use `compose.yml` over `docker-compose.yml` file name
services:
  api:
    build:
      context: .
      target: production

    environment:
      - NODE_ENV=production

    ports:
      - 3000:3000
